
server:
  port: 8085
spring:
  application:
    name: REWARD-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://sa:password_123@cluster0.pecybnt.mongodb.net/?retryWrites=true&w=majority
      database: schools


#eureka setting
eureka:
  client:
    eureka-service-url-defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


