
server:
  port: 8087
spring:
  application:
    name: AVATAR-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://sa:password_123@cluster0.6ygwzay.mongodb.net/?retryWrites=true&w=majority
      database: elements


#eureka setting
eureka:
  client:
    eureka-service-url-defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



