server:
  port: 8761

spring:
  application:
    name: discovery-server

#Eureka setting
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost






