
server:
  port: 8092
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sabkeebar/school-student-config
          clone-on-start: true
          default-label: main

eureka:
  client:
    eureka-service-url-defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true





